version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: mysql:5
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: 1
          MYSQL_DATABASE: dac
          MYSQL_USER: dac
          MYSQL_PASSWORD: dac
      - image: postgres
        environment:
          POSTGRES_USER: dac
          POSTGRES_PASSWORD: dac
          POSTGRES_DB: dac
      - image: microsoft/mssql-server-linux
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: "!Passw0rd"
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: wait for database
          command: sleep 60
      - run:
          name: test
          command: npm run test
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
          - '*'
          - '.*'
            
  deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo     
      - run:
          name: ls
          command: ls
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
  
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
