version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn
     # - run:
     #     name: test
     #     command: npm run test
     # - run:
     #     name: build
     #     command: npm run build  
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      