version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: node run build  
      - save_cache:
          key: node_modules
          paths:
            - node_modules
      