mysql:
  type: mysql
  host: localhost
  user: dac
  password: dac
  database: dac
  
postgres:
  type: postgres
  host: localhost
  user: dac
  password: dac
  database: dac

mssql:
  type: mssql
  host: localhost
  user: sa
  password: '!Passw0rd'
  database: dac